apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: hera-namespace
data:
  alertmanager.yml: |
    global:
      ## 持续多少时间没有触发告警,则认为处于告警问题已经解决状态的时间
      resolve_timeout: 5m
    route:
      ## 这里的标签列表是接收到报警信息后的重新分组标签,例如接收到的报警信息里面有许多具有 cluster=A 这样的标签,可以根据这些标签,将告警信息批量聚合到一个分组里面中
      group_by: ['alertname']
      ## 当一个新的报警分组被创建后,需要等待至少group_wait时间来初始化通知,这种方式可以确保能有足够的时间为同一分组来汇入尽可能多的告警信息,然后将这些汇集的告警信息一次性触发
      group_wait: 10s
      ## 当第一个报警发送后，等待 group_interval 时间来发送新的一组报警信息
      group_interval: 1m
      ## 如果一个报警信息已经发送成功了,则需要等待 repeat_interval 时间才能重新发送
      repeat_interval: 3h
      ## 配置默认的路由规则
      receiver: 'web.hook'
    receivers:
      - name: 'web.hook'
        webhook_configs:
          - url: 'http://prometheus-agent:8080/api/v1/rules/alert/sendAlert'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-hera-namespace
  labels:
    k8s-app: alertmanager-hera-namespace
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/work/alertmanager_hera_namespace_pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - replace your correct node name

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alertmanager-hera-namespace
  namespace: hera-namespace
  labels:
    k8s-app: alertmanager-hera-namespace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      k8s-app: alertmanager-hera-namespace


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: hera-namespace
  labels:
    k8s-app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: alertmanager
  template:
    metadata:
      labels:
        k8s-app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.24.0
          ports:
            - name: http
              containerPort: 9093
          args:
            ## 指定容器中AlertManager配置文件存放地址 (Docker容器中的绝对位置)
            - "--config.file=/etc/alertmanager/alertmanager.yml"
            ## 指定监听的地址及端口
            - '--cluster.advertise-address=0.0.0.0:9093'
            ## 指定数据存储位置 (Docker容器中的绝对位置)
            - "--storage.path=/alertmanager"
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9093
            initialDelaySeconds: 5
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9093
            initialDelaySeconds: 30
            timeoutSeconds: 30
          volumeMounts:
            - name: data
              mountPath: /alertmanager
            - name: config
              mountPath: /etc/alertmanager
        - name: configmap-reload
          image: jimmidyson/configmap-reload:v0.7.1
          args:
            - "--volume-dir=/etc/config"
            - "--webhook-url=http://localhost:9093/-/reload"
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: config
              mountPath: /etc/config
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: alertmanager-hera-namespace
        - name: config
          configMap:
            name: alertmanager-config
